extends RefCounted

## Lightweight source-text localization. Traditional Chinese remains the canonical
## design language; English is resolved at draw time so balance data stays single-source.

const EXACT_EN: Dictionary = {
	"無盡軍勢": "Infinite Legion",
	"荒 原 遠 征": "W I L D L A N D   E X P E D I T I O N",
	"程序生成的無限草原．動作戰鬥．軍隊養成．城堡征服": "Infinite procedural wildlands · Action combat · Army building · Castle conquest",
	"開始遠征": "Start Expedition",
	"讀取上次進度": "Continue",
	"Enter / 點擊開始　　F 全螢幕": "Enter / Tap to Start     F Fullscreen",
	"選擇你的遠征職業": "Choose Your Expedition Class",
	"職業選定後不可切換；可重新開始建立新角色": "Your class is locked for this run; restart to create another hero.",
	"WASD 移動　滑鼠瞄準": "WASD Move     Mouse Aim",
	"左鍵攻擊；擊殺獲得金錢與 XP": "Left Click Attack; defeat enemies for Gold and XP",
	"靠近據點按 E 招募；C 分配技能點": "Press E near a base to recruit; C opens abilities",
	"10 級右鍵技能；攻破城堡後留在圈內": "Right Click unlocks at Lv.10; stay in the circle to capture",
	"M 大地圖　Esc 暫停　F5 儲存": "M Map     Esc Pause     F5 Save",
	"左搖桿移動　右搖桿瞄準並攻擊": "Left stick moves · Right stick aims and attacks",
	"技能鈕施放絕招；上方按鈕開啟功能": "Use Skill for your ultimate · Top buttons open features",
	"靠近據點後點擊招募；能力可分配技能點": "Tap Recruit near a base; spend points under Abilities",
	"軍令鈕循環切換跟隨、防守、攻擊與撤退": "Orders cycle through Follow, Defend, Attack and Retreat",
	"軍令鈕可選跟隨、防守、攻擊、撤退、駐守與攻城": "Orders offer Follow, Defend, Attack, Retreat, Garrison and Siege",
	"裝置接上鍵盤或滑鼠後會自動切換": "Keyboard or mouse input switches controls automatically",
	"隱藏通知（N）": "Hide Notices (N)",
	"顯示通知（N）": "Show Notices (N)",
	"通知關": "Notices Off",
	"通知開": "Notices On",
	"通知已顯示。": "Notices are visible.",
	"輸入作弊碼（T）": "Enter Cheat Code (T)",
	"作弊": "Cheats",
	"輸入作弊碼": "Enter Cheat Code",
	"gold coins：+100000 金幣　 full upgrade：英雄滿級（不升士兵）　 change：保留進度切換職業": "gold coins: +100,000 Gold   full upgrade: max hero only   change: switch class and keep progress",
	"按 Enter 確認；Esc 取消": "Press Enter to confirm; Esc to cancel",
	"作弊碼成功：+100000 金幣": "Cheat accepted: +100,000 Gold",
	"作弊碼成功：英雄已達滿級；士兵強化未變更。": "Cheat accepted: hero maxed; troop upgrades unchanged.",
	"無效的作弊碼。": "Invalid cheat code.",
	"選擇新職業": "Choose a New Class",
	"金錢、等級、士兵、城池與 Boss 進度都會保留": "Gold, level, troops, castles and Boss progress will be preserved.",
	"職業選定後可用 change 作弊碼保留進度切換": "Use the change cheat code later to switch class without resetting progress.",
	"新手指南（H 隱藏）": "Quick Guide (H to hide)",
	"新手指南（點 × 隱藏）": "Quick Guide (tap × to hide)",
	"請旋轉裝置": "Rotate Your Device",
	"橫向模式可使用雙搖桿與完整戰鬥介面": "Turn to landscape for dual-stick controls and the full combat HUD",
	"點擊按鈕操作": "Tap buttons to continue",
	"地圖  M": "Map  M",
	"遠征地圖（M 關閉）": "Expedition Map (M to close)",
	"角色能力": "Hero Abilities",
	"據點招募": "Base Recruitment",
	"遊戲暫停": "Game Paused",
	"繼續遊戲": "Resume",
	"儲存遊戲": "Save Game",
	"讀取遊戲": "Load Game",
	"召喚混沌 Boss": "Summon Chaos Boss",
	"召喚艾歐尼斯": "Summon Aionis",
	"重新開始": "Restart",
	"完結": "The End",
	"製作": "Made by",
	"確定重新開始？": "Restart this expedition?",
	"未儲存的進度將遺失。": "Unsaved progress will be lost.",
	"確定": "Confirm",
	"取消": "Cancel",
	"靜音": "Mute",
	"取消靜音": "Unmute",
	"遠征失敗": "Expedition Failed",
	"左鍵": "LMB",
	"右鍵": "RMB",
	"Lv.10 解鎖": "Unlocks Lv.10",
	"跟隨": "Follow",
	"防守": "Defend",
	"攻擊": "Attack",
	"撤退": "Retreat",
	"駐守": "Garrison",
	"攻城": "Siege",
	"1 跟隨　2 防守　3 攻擊　4 撤退": "1 Follow   2 Defend   3 Attack   4 Retreat",
	"1 跟隨　2 防守　3 攻擊　4 撤退　5 駐守　6 攻城": "1 Follow   2 Defend   3 Attack   4 Retreat   5 Garrison   6 Siege",
	"軍令中心": "Command Center",
	"選擇命令；駐守與攻城會自動鎖定距離玩家最近的對應城堡": "Choose an order; Garrison and Siege automatically lock the nearest matching castle.",
	"跟隨玩家並保持隊形": "Follow the hero in formation",
	"守住目前位置": "Hold the current position",
	"清除指定方向的敵軍": "Attack marked enemies",
	"脫離戰鬥返回玩家": "Break away and return to the hero",
	"進入友方城堡防守": "Defend inside a friendly castle",
	"先清守軍，再拆城牆與主城": "Clear guards, then wall and core",
	"目前沒有可駐守的友方城堡。": "There is no friendly castle to garrison.",
	"目前沒有可攻擊的敵方城堡。": "There is no hostile castle to besiege.",
	"攻城完成：部隊已轉為駐守新城。": "Siege complete: the army is now garrisoning the new city.",
	"駐守城堡失守：部隊已撤回跟隨。": "Garrison lost: the army has returned to Follow.",
	"警告：敵軍正在攻擊友方城堡！": "Warning: enemies are attacking a friendly castle!",
	"駐守軍令：士兵進入城市防線，優先攔截附近來襲敵軍": "Garrison order: troops hold the city perimeter and intercept nearby attackers.",
	"攻城軍令：先清除城市附近守軍，再攻擊外牆與主城": "Siege order: clear nearby defenders before attacking the outer wall and core.",
	"地形修正：石頭與草叢可穿越；樹木仍阻擋，士兵會自動繞開": "Terrain update: rocks and bushes are passable; trees still block and troops reroute.",
	"樹木：仍會阻擋": "Tree: solid",
	"石頭：可直接穿越": "Rock: passable",
	"草叢：可直接穿越": "Bush: passable",
	"攻城（6）會先清除目標附近敵方守軍，再鎖定外牆或主城，避免跳過防線。": "Siege (6) first clears nearby defenders, then targets the outer wall and core to avoid bypassing defenses.",
	"按 E 或 B 開啟招募介面": "Press E or B to recruit",
	"需要靠近出生房屋或友方城堡。": "Move closer to the home or a friendly castle.",
	"請靠近出生房屋或友方城堡招募。": "Recruit near the home or a friendly castle.",
	"軍隊人數已達上限。": "Your army is at capacity.",
	"軍隊上限為 50 + floor(總已擁有城堡等級總和 / 2)": "Army cap is 50 + floor(total owned castle levels / 2).",
	"地形特性：岩石與灌木可通行；樹木會阻擋地面單位，士兵會自動改道躲避樹木。": "Terrain rule: Rocks and bushes are passable; trees block ground units and soldiers automatically reroute.",
	"蟒蛇 Boss 移動已修正，行為更平順。": "Python Boss movement has been fixed and is now smoother.",
	"敵軍移動改為逐畫面平滑位移，行為更穩定。": "Enemies now advance smoothly every frame with less jitter.",
	"金錢不足。": "Not enough gold.",
	"特殊技能會在等級 10 解鎖。": "Your special ability unlocks at level 10.",
	"特殊技能已解鎖！按滑鼠右鍵施放。": "Special ability unlocked! Use Right Click to cast.",
	"遊戲已儲存。": "Game saved.",
	"儲存失敗。": "Save failed.",
	"存檔讀取完成。": "Save loaded.",
	"找不到有效存檔。": "No valid save found.",
	"友方房屋": "Friendly Home",
	"蠻族城堡攻防戰：摧毀後留在範圍內完成佔領": "Barbarian Stronghold: destroy it, then remain in range to capture",
	"蠻族營地": "Barbarian Camp",
	"摧毀後需留在範圍內完成佔領，之後會提供收入與招募。": "Destroy it, then hold the capture zone to gain income and recruitment.",
	"清除守軍與補給箱可獲得額外獎勵，稍後可能重新被佔據。": "Clear the defenders and supply crate for bonus rewards; enemies may reclaim it later.",
	"城堡防禦已瓦解！清除附近敵人並留在範圍內佔領。": "Castle defenses broken! Clear nearby enemies and hold the capture zone.",
	"一座友方城堡已失守！": "A friendly castle has fallen!",
	"警告：友方城堡正在遭受攻擊！": "Warning: a friendly castle is under attack!",
	"蠻族首領已被擊敗！": "The barbarian leader has fallen!",
	"發現蟒蛇 Boss 主巢": "Python Boss Main Lair discovered!",
	"發現腐沼蟒皇・薩迦的巢穴": "Corrupt Python Emperor · Saga's lair discovered!",
	"腐沼蟒皇・薩迦已在此巢穴現身！": "Corrupt Python Emperor · Saga has emerged from this lair!",
	"蟒蛇 Boss 巢穴已清除：腐沼蟒皇・薩迦": "Python Boss Lair cleared: Corrupt Python Emperor · Saga",
	"腐沼蟒皇・薩迦棲息中": "Corrupt Python Emperor · Saga Dwells Here",
	"此巢穴已清除": "Lair Cleared",
	"正在返回巢穴": "Returning to the nest",
	"正在返回巢穴・逐漸恢復生命": "Returning to the nest · Recovering health",
	"暈眩破綻・頭部傷害 +20%": "Stunned opening · Head damage +20%",
	"階段轉換・高額減傷": "Phase shift · Heavy damage reduction",
	"危險預警": "Danger Telegraph",
	"技能後搖": "Skill Recovery",
	"毒潭減速": "Poison Pool Slow",
	"纏繞免疫": "Constrict Immunity",
	"遭到絞蟒纏縛！連點左鍵掙脫／友軍攻擊發光蛇身": "CONSTRICTED! Tap Attack repeatedly / allies strike the glowing coils",
	"遭到絞蟒纏縛！連點右側攻擊區掙脫／友軍攻擊發光蛇身": "CONSTRICTED! Tap the right attack zone repeatedly / allies strike the glowing coils",
	"破綻！頭部傷害 +20%": "Opening! Head damage +20%",
	"腐沼蟒皇・薩迦": "Corrupt Python Emperor · Saga",
	"腐沼蟒皇已被擊敗": "The Corrupt Python Emperor has been defeated!",
	"腐化蟒巢": "Corrupted Serpent Nest",
	"蟒蛇 Boss 主巢": "Python Boss Main Lair",
	"蟒蛇 Boss 主巢・此巢穴已清除": "Python Boss Main Lair · Cleared",
	"蟒蛇 Boss 巢穴": "Python Boss Lair",
	"狩獵": "Hunt",
	"腐毒": "Corruption",
	"狂暴": "Frenzy",
	"狂暴蟒皇": "Frenzied Python Emperor",
	"腐毒正在蔓延": "Corruption is spreading!",
	"蟒皇進入狂暴狀態": "The Python Emperor has entered a frenzy!",
	"越過巢穴界線": "Beyond the nest boundary",
	"失去目標": "Lost target",
	"地形中斷": "Interrupted by terrain",
	"時間結束": "Time expired",
	"目標失效": "Target lost",
	"纏繞中斷": "Constrict interrupted",
	"掙脫成功": "Constrict broken",
	"友軍救援": "Rescued by allies",
	"戰鬥結束": "Battle ended",
	"蟒皇暈眩": "Python Emperor stunned",
	"蟒皇死亡": "Python Emperor defeated",
	"萬象崩滅者・卡厄隆": "Annihilator of All · Kaeron",
	"萬象崩滅者・卡厄隆已在混沌祭壇重生；位置已標示在地圖。": "Annihilator of All · Kaeron has returned at the Chaos Altar; its location is marked on the map.",
	"混沌祭壇": "Chaos Altar",
	"混沌祭壇・已擊破": "Chaos Altar · Cleared",
	"裂界甦醒": "Rift Awakening",
	"星滅狂潮": "Starfall Frenzy",
	"萬象歸零": "Total Annihilation",
	"追獵中": "Hunting",
	"沉睡於混沌祭壇": "Dormant at the Chaos Altar",
	"返回混沌祭壇": "Returning to the Chaos Altar",
	"召喚混沌 Boss 後可前往地圖標記重新挑戰。": "After summoning the Chaos Boss, travel to the map marker to challenge it again.",
	"遠征終章完成；全部科技兵已永久開放。": "Final chapter complete; every technology troop is permanently available.",
	"全部士兵已解鎖：加特林、直升機、轟炸機、UFO": "All troops unlocked: Gatling Gun, Helicopter, Bomber and UFO",
	"擊敗萬象崩滅者・卡厄隆後解鎖。": "Defeat Annihilator of All · Kaeron to unlock this troop.",
	"隕星天降": "Meteor Call",
	"毀滅光炮": "Destruction Beam",
	"連環能量炮": "Energy Barrage",
	"混沌衝擊波": "Chaos Shockwave",
	"黑洞召喚": "Black Hole",
	"異獸召喚": "Summon Monsters",
	"追蹤飛彈": "Homing Missiles",
	"終末雷獄": "Final Lightning",
	"裂界瞬襲": "Rift Dash",
	"諸界終時者・艾歐尼斯": "Aionis · End of All Timelines",
	"艾歐尼斯": "Aionis",
	"無時之庭": "Timeless Court",
	"無時之庭・已擊破": "Timeless Court · Cleared",
	"無時之門": "Timeless Gate",
	"無時之門・擊破混沌 Boss 解鎖": "Timeless Gate · Defeat the Chaos Boss to unlock",
	"時序監視": "Chronal Observation",
	"因果改寫": "Causal Rewrite",
	"諸界崩解": "Realm Collapse",
	"最後時間線": "The Last Timeline",
	"時脈初啟": "Chronal Awakening",
	"時脈裂隙": "Chronal Fracture",
	"因果湧流": "Causal Surge",
	"終末鐘響": "Final Bell",
	"沉睡於無時之庭": "Dormant at the Timeless Court",
	"返回無時之庭": "Returning to the Timeless Court",
	"高危因果預警": "Critical Causality Telegraph",
	"時脈重整": "Chronal Recovery",
	"時間錨": "Time Anchors",
	"核心破防": "Core Exposed",
	"反射護盾": "Causal Mirror",
	"時針斬界": "Clock-Hand Sever",
	"因果追獵": "Causal Hunt",
	"時牢封軍": "Chrono Prison",
	"逆時回生": "Rewind Rebirth",
	"平行軍團": "Parallel Legion",
	"斷界棋盤": "Rift Board",
	"星門炮列": "Star-Gate Barrage",
	"軍勢審判": "Army Judgment",
	"逆因果鏡": "Causal Mirror",
	"十二刻終焉": "Doomsday at the Twelfth Bell",
	"擊敗卡厄隆後，無時之門已開啟；艾歐尼斯的位置已標示在地圖。": "The Timeless Gate has opened after Kaeron's defeat; Aionis is now marked on the map.",
	"諸界終時者・艾歐尼斯已在無時之庭重生；位置已標示在地圖。": "Aionis · End of All Timelines has returned at the Timeless Court; its location is marked on the map.",
	"諸界終時者・艾歐尼斯已被擊敗！": "Aionis · End of All Timelines has been defeated!",
	"時間錨全部破壞：艾歐尼斯破防 5 秒！": "All Time Anchors destroyed: Aionis is exposed for 5 seconds!",
	"4 個時間錨全部毀壞，艾歐尼斯進入5秒破防。": "All four Time Anchors are destroyed. Aionis is exposed for 5 seconds.",
	"5秒破防結束，4個時間錨重新構成。": "The 5-second breach ends and all four Time Anchors reform.",
	"超終局 Boss：四階段、四座時間錨、十種高壓技能。": "Postgame Boss: four phases, four Time Anchors and ten high-pressure abilities.",
	"艾歐尼斯已擊破：無時之庭恢復寂靜。": "Aionis defeated: silence returns to the Timeless Court.",
	"時針斬界展開長刃，形成可持續割裂地帶。": "Clock-Hand Sever opens a sustained cutting lane.",
	"因果追獵啟動，追蹤彈尋找目標。": "Causal Hunt launches missiles that seek their targets.",
	"時牢封軍啟動，空間節點快速聚攏。": "Chrono Prison closes its spatial nodes around the army.",
	"逆時回生施放，時間殘片向周圍反噬。": "Rewind Rebirth releases chronal fragments in every direction.",
	"平行軍團分裂重疊，持續對戰場造成壓迫。": "Parallel Legion overlaps timelines to overwhelm the battlefield.",
	"斷界棋盤展開，近戰傷害將延遲反射。": "Rift Board opens and delays reflected damage.",
	"星門炮列從四方轟射，覆蓋面擴大。": "Star-Gate Barrage fires from every side.",
	"軍勢審判進入多目標鏈式打擊。": "Army Judgment begins a chained multi-target strike.",
	"逆因果鏡展開，部分傷害將被折返。": "Causal Mirror reflects part of incoming damage.",
	"十二刻終焉降臨，時空核心進入斷裂階段。": "The Twelfth Bell descends as the chronal core fractures.",
	"蟒皇返回巢穴": "Python Emperor returning to the nest",
	"絞蟒纏縛": "Python Constriction",
	"蛇影裂地衝": "Rift Serpent Charge",
	"腐牙噬咬": "Venom Fang Bite",
	"腐沼毒潭": "Corrupted Venom Pool",
	"裂骨巨尾": "Bonebreaker Tail",
	"弓箭手": "Archer",
	"法師": "Mage",
	"戰士": "Warrior",
	"快速射擊": "Rapid Shot",
	"火球術": "Fireball",
	"重劍斬": "Heavy Slash",
	"散射箭": "Scatter Volley",
	"火焰飛彈": "Magma Missile",
	"衝刺斬": "Dash Slash",
	"瞄準": "Deadeye",
	"元素親和": "Elemental Affinity",
	"不屈": "Unyielding",
	"暴擊機率+2%，命中時回復少量體力。": "Critical chance +2%; hits restore a small amount of stamina.",
	"命中法術目標有小幅範圍擴散，連鎖傷害機率提升。": "Spell hits spread across a small area and gain a higher chain chance.",
	"生命低於40%時移動速度提高，持續回復小量生命。": "Below 40% HP, move faster and steadily recover a small amount of health.",
	"擅長長距離持續輸出，與群體控制能力互補。": "Sustained long-range damage backed by reliable crowd control.",
	"以大範圍法術控制戰場，對堅韌與群體目標高效。": "Controls the battlefield with wide spells, ideal against tough groups.",
	"前線坦克，擁有高生命與控制，適合吸收壓力。": "A durable frontline tank with strong control and high health.",
	"持續穩定射擊，對單體目標有高穿透率。": "Steady piercing fire against a single target.",
	"以魔法彈造成小範圍爆裂的中距離傷害。": "Mid-range magic that bursts across a small area.",
	"向滑鼠方向揮出扇形重斬，可同時擊退多名近身敵人。": "A heavy frontal sweep that knocks back several nearby enemies.",
	"對前方扇形區域施放多重箭矢，附帶減速效果。": "Fires multiple arrows in a cone and slows targets.",
	"在地面引爆熔岩環域，持續灼燒區域內的敵人。": "Detonates a magma field that repeatedly burns enemies inside.",
	"迅速突進並擊碎鎧甲，短時間降低目標防禦。": "Dashes forward, shattering armor and lowering defense briefly.",
	"劍士": "Swordsman",
	"醫者": "Healer",
	"弓兵": "Ranger",
	"滾石兵": "Boulder Trooper",
	"重甲兵": "Heavy Guard",
	"牧師": "Priest",
	"大砲": "Cannon",
	"重型大砲": "Heavy Cannon",
	"普通大砲": "Standard Cannon",
	"火槍手": "Musketeer",
	"突擊步槍手": "Assault Rifleman",
	"坦克": "Tank",
	"火箭炮": "Rocket Artillery",
	"加特林": "Gatling Gun",
	"直升機": "Helicopter",
	"轟炸機": "Bomber",
	"UFO": "UFO",
	"敵軍火槍手": "Enemy Musketeer",
	"敵軍突擊步槍手": "Enemy Assault Rifleman",
	"敵軍坦克": "Enemy Tank",
	"敵軍火箭炮": "Enemy Rocket Artillery",
	"敵軍加特林": "Enemy Gatling Gun",
	"敵軍直升機": "Enemy Helicopter",
	"敵軍轟炸機": "Enemy Bomber",
	"敵軍 UFO": "Enemy UFO",
	"砲兵要塞": "Artillery Citadel",
	"火器堡壘": "Firearms Fortress",
	"鋼鐵軍城": "Steel Warhold",
	"巨壁機關城": "Grandwall Arsenal",
	"天空戰爭堡": "Sky War Fortress",
	"星界終焉城": "Astral Final Citadel",
	"外牆": "Outer Wall",
	"外牆已突破": "Outer Wall Breached",
	"友軍相位屏障・可自由通行": "Friendly Phase Barrier · Free Passage",
	"UFO 光柱": "UFO Beam",
	"平衡穩定的近戰主力，適合大規模交戰。": "Reliable frontline infantry for large battles.",
	"行軍中的持續治療來源，擅長維持隊伍續航。": "Sustained mobile healing that keeps the army fighting.",
	"穩定遠程輸出，可壓制敵方前鋒。": "Steady ranged pressure against enemy frontlines.",
	"投出可穿透多名敵人且逐次衰減傷害的大型滾石。": "Rolls a huge boulder through multiple enemies with damage falloff.",
	"低血但高爆發的法術遠距單位。": "A fragile ranged caster with high burst damage.",
	"高韌性突破型戰士，適合帶隊衝鋒。": "A resilient breakthrough fighter who leads charges.",
	"以長時間儀式復活仍留有墓碑的友方士兵。": "Revives fallen allies whose tombstones remain.",
	"昂貴、脆弱且緩慢的超遠程攻城火力平台。": "A costly, fragile and slow extreme-range siege platform.",
	"玩家專用的加固重砲；威力與爆炸範圍高於城堡普通大砲。": "A player-only reinforced cannon with more damage and a wider blast than the castle's standard cannon.",
	"裝填很慢，但單發威力與射程極高的精準射手。": "A precise long-range shooter with very slow reloads and devastating single shots.",
	"以高速連射壓制地面與空中目標的現代步兵。": "Modern infantry using rapid fire to suppress ground and air targets.",
	"履帶重甲載具；生命與砲擊傷害高，但射速緩慢。": "A heavily armored tracked vehicle with high health and powerful slow cannon fire.",
	"長距離發射大型火箭，造成極高且寬廣的爆炸傷害。": "Launches long-range heavy rockets for extreme damage across a wide blast area.",
	"20 級城堡開始部署的慢速範圍砲兵。": "Slow area artillery deployed by castles from level 20 onward.",
	"裝填緩慢但單發傷害極高。": "Reloads slowly, but each shot deals extremely high damage.",
	"高速連射且傷害高的遠程威脅。": "A high-damage ranged threat with rapid automatic fire.",
	"血量與護甲極高的履帶砲擊載具。": "A tracked cannon vehicle with extremely high health and armor.",
	"以極慢射速換取極高範圍爆炸傷害。": "Trades a very slow fire rate for extreme wide-area explosive damage.",
	"射速極快、單發傷害一般的旋轉機槍。": "A rotary gun with extreme fire rate and moderate damage per round.",
	"高速空中加特林平台，只有遠程攻擊能命中。": "A fast airborne Gatling platform that only ranged attacks can hit.",
	"沿地面連續投彈的重型空中單位。": "A heavy aircraft that drops a sequence of bombs across the ground.",
	"從空中垂直照射可躲避、但不會秒殺玩家的光柱。": "Projects a dodgeable vertical beam that hurts but never instantly kills the player.",
	"20 級砲兵要塞：20 名守軍・普通大砲已部署": "Lv.20 Artillery Citadel: 20 guards · Standard Cannons deployed",
	"30 級火器堡壘：重傷害火槍手・高速突擊步槍手": "Lv.30 Firearms Fortress: heavy Musketeers · rapid Assault Riflemen",
	"35 級鋼鐵軍城：重甲坦克・極高範圍火箭炮": "Lv.35 Steel Warhold: armored Tanks · extreme-area Rocket Artillery",
	"40 級巨壁機關城：必須先摧毀外牆・高速加特林": "Lv.40 Grandwall Arsenal: breach the Outer Wall first · rapid Gatling Guns",
	"45 級天空戰爭堡：遠程才能命中・直升機與連續轟炸": "Lv.45 Sky War Fortress: ranged attacks only · Helicopters and bombing runs",
	"50 級星界終焉城：UFO 垂直光柱・碰觸受傷但不會秒殺": "Lv.50 Astral Final Citadel: vertical UFO beams hurt, but never instantly kill",
	"玩家科技招募：重型大砲傷害 112 ＞ 普通大砲傷害 72": "Player Technology: Heavy Cannon damage 112 > Standard Cannon damage 72",
	"實戰比較：重型大砲 112 傷害 ＞ 普通大砲 72 傷害": "Live-fire comparison: Heavy Cannon 112 damage > Standard Cannon 72 damage",
	"測試場景不會覆寫玩家存檔。": "Test showcases never overwrite your player save.",
	"步兵": "Infantry",
	"擲彈手": "Grenadier",
	"狂戰士": "Berserker",
	"重甲敵": "Armored Brute",
	"薩滿": "Shaman",
	"酋長": "Chieftain",
	"最常見的敵方士兵，數量大但組織差。": "Common enemy infantry: numerous, but poorly organized.",
	"輕甲遠程敵人，常作為掩護與壓制。": "A lightly armored ranged enemy used for cover and suppression.",
	"可投擲爆裂投射物並打斷後排隊形。": "Throws explosive projectiles that disrupt rear formations.",
	"近身突進，短時間內傷害和速度顯著提升。": "Rushes into melee with a brief surge of damage and speed.",
	"防禦高、移動慢的前線威脅。": "A slow frontline threat with heavy defenses.",
	"具有群體輔助能力，能加速自軍。": "Supports nearby allies and increases their speed.",
	"首領型單位，會嘗試保護周邊敵軍。": "A leader unit that protects nearby enemies.",
	"攻擊力": "Attack Power",
	"防禦力": "Defense Power",
	"提高單位基礎生命。": "Increases base unit health.",
	"提升所有已招募隊伍的傷害輸出。": "Increases damage dealt by all recruited troops.",
	"減少受到的傷害，增加生存時間。": "Reduces incoming damage and improves survivability.",
	"提高行軍與追擊能力。": "Improves marching and pursuit speed.",
	"降低普通攻擊冷卻；設有安全下限。": "Reduces normal-attack cooldown, down to a safe minimum.",
	"此能力已達上限。": "This ability is already at its maximum.",
	"復活": "Revived",
	"每點 +5% 傷害": "Each point: +5% damage",
	"每點 +2 防禦（最高減傷 70%）": "Each point: +2 defense (70% damage reduction cap)",
	"每點 +8% 最大生命": "Each point: +8% max HP",
	"每點 +2.5%（上限 +30%）": "Each point: +2.5% (cap +30%)",
	"每點 +6% 攻速（最低冷卻 0.16 秒）": "Each point: +6% attack speed (minimum cooldown 0.16s)",
	"Esc 返回　F 全螢幕": "Esc Back     F Fullscreen",
	"地圖": "Map",
	"說明": "Guide",
	"能力": "Abilities",
	"招募": "Recruit",
	"軍令": "Orders",
	"暫停": "Pause",
	"關閉": "Close",
	"移動": "Move",
	"瞄準攻擊": "Aim / Attack",
	"技能": "Skill",
	"互動": "Interact",
	"中文": "中文",
	"英文": "English",
}

const REPLACEMENTS_EN: Array = [
	["駐軍", "Garrison"],
	["駐守", "Garrison"],
	["攻城", "Siege"],
	["跟隨", "Follow"],
	["防守", "Defend"],
	["撤退", "Retreat"],
	["重型大砲", "Heavy Cannon"],
	["普通大砲", "Standard Cannon"],
	["突擊步槍手", "Assault Rifleman"],
	["火槍手", "Musketeer"],
	["火箭炮", "Rocket Artillery"],
	["敵軍", "Enemy "],
	["友方", "Friendly "],
	["城牆 -", "Wall -"],
	[" 級城堡外牆已突破！現在可以攻擊主城。", " Castle outer wall breached! The core can now be attacked."],
	["歡迎，", "Welcome, "],
	["！離開安全區並探索荒原。", "! Leave the safe zone and explore the wildlands."],
	["世界 Boss 獎勵：", "World Boss Reward: "],
	["戰敗：損失 ", "Defeat penalty: Lost "],
	["城堡收入 +", "Castle income +"],
	["城堡佔領完成！獎勵 ", "Castle captured! Reward: "],
	[" 金幣並開始產生收入。", " Gold; income has begun."],
	["營地已清除：", "Camp cleared: "],
	["補給箱：", "Supply crate: "],
	[" 金幣並恢復生命。", " Gold and restored HP."],
	[" 金幣、", " Gold · "],
	[" 金  +", " Gold  +"],
	["蟒皇進入第 ", "Python Emperor entered Phase "],
	[" 階段：", ": "],
	["狂暴蟒皇", "Frenzied Python Emperor"],
	["腐沼蟒皇", "Corrupt Python Emperor"],
	["蟒蛇 Boss 巢穴 Lv.", "Python Boss Lair Lv."],
	["Boss 巢穴 ", "Boss Lair "],
	["蟒皇", "Python Emperor"],
	["升級！目前等級 ", "Level up! Current level "],
	["，獲得技能點。", " and gained 1 Skill Point."],
	["招募 ", "Recruited "],
	["部隊命令：", "Army order: "],
	["軍隊已達上限，暫時無法復活士兵。", "Army capacity reached; allies cannot be revived yet."],
	["已在最近的友方據點復活，獲得 5 秒保護。", "Revived at the nearest friendly base with 5 seconds of protection."],
	["已扣除目前金幣的 10%，等級與存檔進度不受影響", "Lost 10% of current gold; level and saved progress are preserved"],
	["將在 ", "Respawning in "],
	[" 秒後於最近的友方據點復活", " seconds at the nearest friendly base"],
	["第 ", "Phase "],
	[" 階段・", " · "],
	["階段", "Phase"],
	["友方城堡", "Friendly Castle"],
	["蠻族城堡", "Barbarian Castle"],
	["佔領進度", "Capture"],
	["軍隊上限", "Army Cap"],
	["剩餘技能點", "Available Points"],
	["技能點", "Skill Points"],
	["技能冷卻 ", "Ability cooldown "],
	["已解鎖：", "Unlocked: "],
	["　冷卻 ", " · Cooldown "],
	["特殊技能將於等級 10 解鎖", "Special ability unlocks at level 10"],
	["已解鎖", "Unlocked"],
	["冷卻", "Cooldown"],
	["命令：", "Order: "],
	["軍隊", "Army"],
	["金幣", "Gold"],
	["已有", "Owned"],
	["傷害", "Damage"],
	["射程", "Range"],
	["攻擊速度", "Attack Speed"],
	["攻速", "Atk Speed"],
	["攻擊", "Attack"],
	["防禦", "Defense"],
	["生命值", "Max HP"],
	["生命", "HP"],
	["移動速度", "Move Speed"],
	["移速", "Move Speed"],
	["速度", "Speed"],
	["普通：", "Normal: "],
	["10 級：", "Lv.10: "],
	["選擇 ", "Choose "],
	["目前：", "Current: "],
	["Shift 點擊可購買 5 名", "Shift-click to buy 5"],
	["音量", "Volume"],
	["擊殺", "Defeated"],
	["城堡", "Castles"],
	["尾部", "Tail"],
	["身軀", "Body"],
	["頭部", "Head"],
	["毒素 ×", "Poison ×"],
	["已清除", "Cleared"],
	[" 秒", "s"],
	["秒", "s"],
	["地形特性：岩石與灌木可通行；樹木會阻擋地面單位，士兵會自動改道躲避樹木。", "Terrain rule: Rocks and bushes are passable; trees block ground units and soldiers automatically reroute."],
	["Python Boss", "Python Boss"],
	["平滑位移", "smooth movement"],
	["　", " · "],
	["，", ", "],
	["、", " · "],
	["：", ": "],
	["。", "."],
	["！", "!"],
	["（", " ("],
	["）", ")"],
	["金", "Gold"],
]


static func translate(source: String, language: String) -> String:
	if language != "en" or source.is_empty():
		return source
	if EXACT_EN.has(source):
		return str(EXACT_EN[source])
	var result := source
	for replacement_value in REPLACEMENTS_EN:
		var replacement: Array = replacement_value
		result = result.replace(str(replacement[0]), str(replacement[1]))
	for chinese_value in EXACT_EN.keys():
		var chinese := str(chinese_value)
		if result.contains(chinese):
			result = result.replace(chinese, str(EXACT_EN[chinese]))
	return result
